using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GitHubSearchApi.Models
{
    public class RepositoryEntry
    {
        public bool bookmarked;
        public int id; // 2346262,
        public string node_id; // "MDEwOlJlcG9zaXRvcnkyMzQ2MjYy",
        public string name; // "mongoid-searchable",
        public string full_name; // "jcoene/mongoid-searchable",
        public bool @private; // false,
        public OwnerEntry owner;
        public string html_url; // "https://github.com/jcoene/mongoid-searchable",
        public string description; // "Simple keyword search for your Mongoid models",
        public bool fork; // false,
        public string url; // "https://api.github.com/repos/jcoene/mongoid-searchable",
        public string forks_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/forks",
        public string keys_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/keys{/key_id}",
        public string collaborators_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/collaborators{/collaborator}",
        public string teams_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/teams",
        public string hooks_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/hooks",
        public string issue_events_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/issues/events{/number}",
        public string events_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/events",
        public string assignees_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/assignees{/user}",
        public string branches_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/branches{/branch}",
        public string tags_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/tags",
        public string blobs_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/git/blobs{/sha}",
        public string git_tags_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/git/tags{/sha}",
        public string git_refs_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/git/refs{/sha}",
        public string trees_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/git/trees{/sha}",
        public string statuses_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/statuses/{sha}",
        public string languages_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/languages",
        public string stargazers_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/stargazers",
        public string contributors_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/contributors",
        public string subscribers_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/subscribers",
        public string subscription_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/subscription",
        public string commits_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/commits{/sha}",
        public string git_commits_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/git/commits{/sha}",
        public string comments_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/comments{/number}",
        public string issue_comment_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/issues/comments{/number}",
        public string contents_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/contents/{+path}",
        public string compare_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/compare/{base}...{head}",
        public string merges_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/merges",
        public string archive_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/{archive_format}{/ref}",
        public string downloads_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/downloads",
        public string issues_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/issues{/number}",
        public string pulls_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/pulls{/number}",
        public string milestones_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/milestones{/number}",
        public string notifications_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/notifications{?since,all,participating}",
        public string labels_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/labels{/name}",
        public string releases_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/releases{/id}",
        public string deployments_url; // "https://api.github.com/repos/jcoene/mongoid-searchable/deployments",
        public DateTime created_at; // "2011-09-08T03:51:11Z",
        public DateTime updated_at; // "2019-07-09T14:20:48Z",
        public DateTime pushed_at; // "2011-10-01T21:31:09Z",
        public string git_url; // "git://github.com/jcoene/mongoid-searchable.git",
        public string ssh_url; // "git@github.com:jcoene/mongoid-searchable.git",
        public string clone_url; // "https://github.com/jcoene/mongoid-searchable.git",
        public string svn_url; // "https://github.com/jcoene/mongoid-searchable",
        public string homepage; // "https://github.com/jcoene/mongoid-searchable",
        public int size; // 180,
        public int stargazers_count; // 12,
        public int watchers_count; // 12,
        public string language; // "Ruby",
        public bool has_issues; // true,
        public bool has_projects; // true,
        public bool has_downloads; // true,
        public bool has_wiki; // false,
        public bool has_pages; // false,
        public int forks_count; // 5,
        public string mirror_url; // null,
        public bool archived; // false,
        public bool disabled; // false,
        public int open_issues_count; // 2,
        public LicenseEntry license;
        public int forks; // 5,
        public int open_issues; // 2,
        public int watchers; // 12,
        public string default_branch; // "master",
        public double score; // 1.0
    }
}